root: true
env:
  browser: true
  node: true
  commonjs: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
rules:
  semi: 1
  camelcase: 1
  arrow-spacing: [1, {before: true, after: true}]
  prefer-arrow-callback: 1
  prefer-template: 1
  quotes: [1, single, {allowTemplateLiterals: true}]
  jsx-quotes: [1, prefer-double]
