version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run:
          name: "Print out versions"
          command: |
            #/bin/sh
            echo "node -v = $(node -v)"
            echo "npm -v = $(npm -v)"
            echo "yarn --version = $(yarn --version)"
      - run:
          name: "Add private token to npmrc"
          command: echo "//npmregistry.density.rodeo/:_authToken=${PRIVATE_NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run tests"
          command: yarn test

  branch-preview:
    docker:
      - image: circleci/node:8.9
    steps:
      - run:
          name: "Set branch-preview url in package.json"
          command: |
            #!/bin/sh -e
            jq ".homepage = \"https://dashboard.density.rodeo/branches/$BRANCH\"" package.json > /tmp/pkg
            mv /tmp/pkg package.json
      - run:
          name: "Build branch-preview dashboard"
          command: | 
            #!/bin/sh -e
            REACT_APP_ENVIRONMENT="staging" \
            NODE_ENV=production \
            yarn build
      - run:
          name: "Push branch-preview dashboard"
          command: |
            #!/bin/sh -e
            BRANCH="$(echo $CIRCLE_BRANCH | tr '/' '-')"
            aws s3 sync build/ s3://dashboard.density.rodeo/branches/${BRANCH} --region us-east-1
      - run:
          name: "Post status to github commit with link to preview dashboard."
          command: |
            curl -X POST \
            -d "{\"state\":\"success\", \"context\": \"ci-preview\", \"target_url\": \"https://dashboard.density.rodeo/branches/$BRANCH\"}" \
            -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
            https://api.github.com/repos/densityco/dashboard/statuses/${CIRCLE_SHA1}

  staging:
    docker:
      - image: circleci/node:8.9
    steps:
      - run:
          name: "Build staging dashboard"
          command: | 
            #!/bin/sh -e

            # NOTE: These are not secrets, they're public identifiers that are built into the
            # final webapp.
            REACT_APP_MIXPANEL_TOKEN="eb87b138bbb5d556fcf53bebac24b935" \
            REACT_APP_GA_TRACKING_CODE="UA-77313135-1" \
            REACT_APP_ENVIRONMENT="staging" \
            NODE_ENV=production \
            yarn build
      - run:
          name: "Push staging dashboard"
          command: | 
            echo "* Installing amazon's cli..."
            sudo apt-get update
            sudo apt-get install -y awscli

            echo "* Copying to S3..."
            aws s3 sync build/ s3://dashboard.density.rodeo/ --region us-east-1

  production:
    docker:
      - image: circleci/node:8.9
    steps:
      - run:
          name: "Build production dashboard"
          command: | 
            #!/bin/sh -e
            echo "Will (eventually) build production dashboard"
            echo "Or should this somehow promote a staging build? I don't know if that's possible though given that staging builds have different inputs."
      - run:
          name: "Push production dashboard"
          command: | 
            echo "Will (eventually) push production dashboard"



workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build

      # For all non-trunk branches, build/deploy to `https://dashboard.density.rodeo/branches/BRANCH`
      - branch-preview:
          requires:
            - build
          filters:
            branches:
              ignore: trunk
      # Trunk is built and deployed to `https://dashboard.density.rodeo`
      - staging:
          requires:
            - build
          filters:
            branches:
              only: trunk

      # Wait for someone to approve the change to move it into production
      - hold-production:
        type: approval
        requires:
          - build
          - staging

      - production:
        requires:
          - build
          - staging
          - hold-production
        filters:
          branches:
            only: trunk
