version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6.11
    steps:
      - checkout
      - run:
          name: "Add private token to npmrc"
          command: echo "//npmregistry.density.rodeo/:_authToken=${PRIVATE_NPM_TOKEN}" >> ~/.npmrc
      - run:
          name: "Install dependencies"
          command: yarn
      - run:
          name: "Run tests"
          command: yarn test
      - run:
          name: "Build dashboard"
          command: |
            echo "node -v = $(node -v)"
            echo "npm -v = $(npm -v)"
            echo "yarn --version = $(yarn --version)"

            if [ "$CIRCLE_BRANCH" == "master" ]; then
              # Build dashboard in production
              echo "* Building production dashboard..."

              # NOTE: These are not secrets, they're public identifiers that are built into the
              # final webapp.
              REACT_APP_MIXPANEL_TOKEN="eb87b138bbb5d556fcf53bebac24b935" \
              REACT_APP_GA_TRACKING_CODE="UA-77313135-1" \
              REACT_APP_ENVIRONMENT="production" \
              NODE_ENV=production \
              yarn build

              echo "* Installing amazon's cli..."
              sudo apt-get update
              sudo apt-get install -y awscli

              echo "* Copying to S3..."
              aws s3 sync build/ s3://dashboard.density.io/ --region us-east-1
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
              # Build dashboard in staging
              echo "* Building staging dashboard..."

              # NOTE: These are not secrets, they're public identifiers that are built into the
              # final webapp.
              REACT_APP_MIXPANEL_TOKEN="eb87b138bbb5d556fcf53bebac24b935" \
              REACT_APP_GA_TRACKING_CODE="UA-77313135-1" \
              REACT_APP_ENVIRONMENT="staging" \
              NODE_ENV=production \
              yarn build

              echo "* Installing amazon's cli..."
              sudo apt-get update
              sudo apt-get install -y awscli

              echo "* Copying to S3..."
              aws s3 sync build/ s3://dashboard.density.rodeo/ --region us-east-1
            else
              # Build dashboard for an arbitrary branch
              echo "* Finding / generating branch folder with uuid."
              BRANCH="$(echo $CIRCLE_BRANCH | tr '/' '-')"
              echo "* BRANCH = $BRANCH"

              echo "* Adding homepage to package.json for create-react-app deploy..."
              jq ".homepage = \"https://densityco.github.io/dashboard/$BRANCH\"" package.json > /tmp/pkg
              mv /tmp/pkg package.json

              echo "* Building dashboard..."
              npm run build

              echo "* Copying to dashboard..."
              sudo apt-get update
              sudo apt-get install -y awscli
              aws s3 sync build/ s3://dashboard.density.rodeo/branches/$BRANCH --region us-east-1

              echo "***************************"
              echo "* Preview URL: https://dashboard.density.rodeo/branches/$BRANCH"
              echo "***************************"

              # Post a link to the branch as a comment in the PR
              echo "* Pull requests this commit is part of: $CI_PULL_REQUESTS"
              export IFS=","
              for pr in $CI_PULL_REQUESTS; do
                num="$(echo $pr | awk -F'/' '{ print $NF }')"
                if [ -z \
                  "$(curl -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
                  https://api.github.com/repos/densityco/internal-dashboard/issues/$num/comments \
                  | jq .[].user.login \
                  | grep density-machine-user)" ]; then

                  curl -X POST \
                  -d "{\"body\": \"Here is a link to the built dashboard: https://densityco.github.io/dashboard/$BRANCH\"}" \
                  -H "Authorization: Bearer $GITHUB_MACHINE_USER_TOKEN" \
                  https://api.github.com/repos/densityco/dashboard/issues/$num/comments

                fi
              done
            fi
