enum SpaceReportsActionTypes {
  SPACES_SET_REPORT_CONTROLLERS = 'SPACES_SET_REPORT_CONTROLLERS',
  SPACES_UPDATE_REPORT_CONTROLLER = 'SPACES_UPDATE_REPORT_CONTROLLER',
};

export default SpaceReportsActionTypes;
